apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-config-server
  template:
    metadata:
      labels:
        app: cloud-config-server
    spec:
      containers:
      - name: cloud-config-server
        image: chirag407/app-cloud-config-server:0.0.1
        ports:
          - containerPort: 9296

---

apiVersion: v1
kind: Service
metadata:
  name: cloud-config-server-svc
spec:
  selector:
    app: cloud-config-server
  type: ClusterIP  
  ports:
  - port: 80
    targetPort: 9296