apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-gateway
  template:
    metadata:
      labels:
        app: cloud-gateway
    spec:
      containers:
      - name: cloud-gateway
        image: chirag407/app-cloud-gateway:0.0.1
        ports:
          - containerPort: 9191

---

apiVersion: v1
kind: Service
metadata:
  name: cloud-gateway-svc
spec:
  selector:
    app: cloud-gateway
  type: LoadBalancer  
  ports:
  - port: 80
    targetPort: 9191