apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-order-service
  template:
    metadata:
      labels:
        app: user-order-service
    spec:
      containers:
      - name: user-order-service
        image: chirag407/app-user-order-service:0.0.1
        ports:
          - containerPort: 9003

---

apiVersion: v1
kind: Service
metadata:
  name: user-order-service-svc
spec:
  selector:
    app: user-order-service
  type: ClusterIP  
  ports:
  - port: 80
    targetPort: 9003